name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.set-output.outputs.matrix}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build Debug
      run: dotnet build -c Debug 
    - name: Run Tests
      run: dotnet test --no-restore -c Debug -v normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish test coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Atropos.Tests/TestResults/coverage.info   
    - name: Build Release
      run: dotnet build -c Release 
    - name: List Benchmarks
      run: cd Atropos.Benchmarks; sudo dotnet run -c Release --no-build --list Flat > benchmarks.txt
    - name: Display Benchmarks
      run: cd Atropos.Benchmarks; cat benchmarks.txt
    - name: set-output
      run: echo "::set-output name=matrix::{\"benchmark\":$(cat Atropos.Benchmarks/benchmarks.txt | jq -cR . | jq -cs)}"
  benchmark:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.build.outputs.matrix)}}
    steps:
    - name: Run benchmarks
      run: cd Atropos.Benchmarks; sudo dotnet run -c Release --no-build --filter ${{matrix.benchmark}};
    - name: Check benchmark results
      run: ls ./Atropos.Benchmarks/BenchmarkDotNet.Artifacts/results/*.csv
    - name: Update benchmark results 
      uses: EndBug/add-and-commit@v6
      with:
        message: 'Updating the benchmark results'
        add: './Atropos.Benchmarks/BenchmarkDotNet.Artifacts/results/*-report.csv'
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
    - name: Warm-up R
      run: cd Atropos.Benchmarks; Rscript Warmup.R
    - name: Process benchmarks output with R
      run: cd Atropos.Benchmarks; Rscript RibbonGraph.R
    - name: Update benchmark charts
      uses: EndBug/add-and-commit@v6
      with:
        message: 'Updating the benchmark charts'
        add: './Atropos.Benchmarks/*.png'
      env:
      # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
