name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs: 
      matrix: ${{ steps.set-output.outputs.matrix}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build 
      run: dotnet build -c Debug 
    - name: Run Tests
      run: dotnet test --no-restore -c Debug -v normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
    - name: Publish test coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./Atropos.Tests/TestResults/coverage.info   
    - name: List Benchmarks
      run: cd Atropos.Benchmarks; sudo dotnet run -c Debug --no-build --list Flat | jq -cR "split(\".\") | .[0:4] | join(\".\")" | jq -cs unique > benchmarks.json
    - name: Display Benchmarks
      run: cat Atropos.Benchmarks/benchmarks.json
    - name: Send the list of benchmarks to the benchmark job
      id: set-output
      run: echo "::set-output name=matrix::{\"benchmark\":$(cat Atropos.Benchmarks/benchmarks.json)}"
  graphs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@v1
    - name: Warm-up R
      run: cd Atropos.Benchmarks; Rscript Warmup.R
    - name: Process benchmarks output with R
      run: cd Atropos.Benchmarks; Rscript RibbonGraph.R
    - name: Update benchmark charts
      uses: EndBug/add-and-commit@v6
      with:
        message: 'Updating the benchmark charts'
        add: './Atropos.Benchmarks/*.png'
